# Generated by Django 4.1.4 on 2023-01-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usercontacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontacts',
            name='request_accepted',
            field=models.BooleanField(),
        ),
    ]
