# Generated by Django 4.1.4 on 2023-01-12 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_contactbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbook',
            name='user1',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactbook',
            name='user2',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
