# Generated by Django 4.1.4 on 2022-12-11 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_name', models.CharField(blank=True, max_length=120, null=True)),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatUserAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversation.chatconversation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMG', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('DOCUMENT', 'Document')], max_length=60)),
                ('message_text', models.TextField()),
                ('message_media_address', models.TextField(max_length=500)),
                ('creation_date', models.DateField()),
                ('edition_date', models.DateField()),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversation.chatconversation')),
            ],
        ),
    ]
