# Generated by Django 4.1.4 on 2023-01-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privateconversation',
            old_name='user_1_id',
            new_name='user_1',
        ),
        migrations.RenameField(
            model_name='privateconversation',
            old_name='user_2_id',
            new_name='user_2',
        ),
    ]
