# Generated by Django 4.1.4 on 2023-01-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_rename_user_1_id_privateconversation_user_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privateconversation',
            old_name='user_1',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='privateconversation',
            old_name='user_2',
            new_name='user2',
        ),
    ]
